<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB2PVrxE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB2PVrxE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB2PVrxE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB2PVrxE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB2PVrxE\App_KernelDevDebugContainer([
    'container.build_hash' => 'B2PVrxE',
    'container.build_id' => 'd895b804',
    'container.build_time' => 1627288837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB2PVrxE');
